// components/WorkExperience.tsx
import { useTranslations } from 'next-intl';

const jobNames = ['metran', 'infowise', 'baltInfoCom', 'metran0'] as const;

export default function WorkExperience() {
  const t = useTranslations();

  return (
    <section className='section-block' aria-labelledby='work-experience-heading'>
      <h2 id='work-experience-heading' className='section-heading'>
        {t('work-experience.title')}
      </h2>

      <ol className='flex flex-col'>
        {jobNames.map((job, index) => {
          const description = t(`work-experience.${job}.description`);

          return (
            <li
              key={job}
              className={`grid gap-2 py-[var(--space-entry)] sm:grid-cols-[minmax(9rem,11rem)_1fr] sm:gap-x-10 sm:gap-y-1 ${
                index > 0 ? 'border-divider border-t' : ''
              }`}
            >
              <p className='text-meta sm:pt-1'>{t(`work-experience.${job}.period`)}</p>
              <div>
                <h3 className='font-display text-subheading font-semibold leading-snug text-ink'>
                  {t(`work-experience.${job}.name`)}
                </h3>
                <p className='text-caption mt-1'>{t(`work-experience.${job}.position`)}</p>
                {description ? <p className='mt-3'>{description}</p> : null}
              </div>
            </li>
          );
        })}
      </ol>
    </section>
  );
}

// components/work-experience.vue
<template>
  <section>
    <h2 class="mb-4 text-2xl font-semibold">{{ $t('work-experience.title') }}</h2>
    <ul class="grid grid-cols-1 gap-6 md:grid-cols-2">
      <li v-for="job in jobNames" :key="job" class="rounded bg-zinc-800 p-4">
        <h3 class="text-lg font-bold">{{ $t(`work-experience.${job}.name`) }}</h3>
        <p class="text-sm text-zinc-400">
          {{ $t(`work-experience.${job}.position`) }} | {{ $t(`work-experience.${job}.period`) }}
        </p>
        <p class="mt-2 text-zinc-300">{{ $t(`work-experience.${job}.description`) }}</p>
      </li>
    </ul>
  </section>
</template>

<script setup lang="ts">
const jobNames = ['metran', 'infowise', 'baltInfoCom', 'metran0'];
</script>
